### ISSUE TITLE
热气球挂机报错“请先获取京东账号一cookie”

### ISSUE THREAD

**Issue by beyond510** [jiulan/platypus#6]
我用的是青龙，想问一下怎么解决这个问题
![image](https://user-images.githubusercontent.com/28379540/128542474-032762d2-8cb8-4dd3-84db-b2ed0c141ba8.png)

**Comment by jiulan** [comment]
挂机任务我移除了    热气球上限500 单独挂机意义并不大  合并到cfd脚本中了   


> 我用的是青龙，想问一下怎么解决这个问题
> ![image](https://user-images.githubusercontent.com/28379540/128542474-032762d2-8cb8-4dd3-84db-b2ed0c141ba8.png)
